import { writable } from 'svelte/store'

const contacts = [
  {
    _id: 1,
    name: 'Aaron Chatukuta',
    isCorporate: false,
    notes: '',
    vatOrBpNo: '',
    email: '',
    phone: '077 346 2562',
    address: '',
    balanceDue: 270,
    totalReceipts: 3000,
    isActive: false,
  },
  {
    _id: 2,
    name: 'Abby',
    isCorporate: false,
    notes: '',
    vatOrBpNo: '',
    email: '',
    phone: '077 197 8809',
    address: '',
    balanceDue: 100,
    totalReceipts: 150,
    isActive: false,
  },
  {
    _id: 3,
    name: 'Abygirl Mahlangu',
    isCorporate: false,
    notes: '',
    vatOrBpNo: '',
    email: '',
    phone: '+263 77 366 4291',
    address: '',
    balanceDue: 3,
    totalReceipts: 15,
    isActive: false,
  },
  {
    _id: 4,
    name: 'ADB',
    isCorporate: true,
    notes: '',
    vatOrBpNo: '',
    email: '',
    phone: '+263 77 328 0244',
    address: '',
    balanceDue: 0,
    totalReceipts: 0,
    isActive: false,
  },
  {
    _id: 5,
    name: 'Africa Paint',
    isCorporate: true,
    notes: '',
    vatOrBpNo: '',
    email: '',
    phone: '077 228 3837',
    address: '',
    balanceDue: 0,
    totalReceipts: 0,
    isActive: false,
  },
  {
    _id: 6,
    name: 'Aleck',
    isCorporate: false,
    notes: '',
    vatOrBpNo: '',
    email: '',
    phone: '077 400 7750',
    address: '',
    balanceDue: 0,
    totalReceipts: 0,
    isActive: false,
  },
  {
    _id: 7,
    name: 'All Colours',
    isCorporate: true,
    notes: '',
    vatOrBpNo: '',
    email: '',
    phone: '+263 71 531 9275',
    address: '',
    balanceDue: 0,
    totalReceipts: 0,
    isActive: false,
  },
  {
    _id: 8,
    name: 'Alletin',
    isCorporate: true,
    notes: '',
    vatOrBpNo: '',
    email: '',
    phone: '071 906 4447',
    address: '',
    balanceDue: 0,
    totalReceipts: 0,
    isActive: false,
  },
  {
    _id: 9,
    name: 'Alpha Mineral Water',
    isCorporate: false,
    notes: '',
    vatOrBpNo: '',
    email: '',
    phone: '+263 77 979 6970',
    address: '',
    balanceDue: 0,
    totalReceipts: 0,
    isActive: false,
  },
  {
    _id: 10,
    name: 'Amandlethu',
    isCorporate: false,
    notes: '',
    vatOrBpNo: '',
    email: '',
    phone: '+263 71 678 8102',
    address: '',
    balanceDue: 13,
    totalReceipts: 50,
    isActive: false,
  },
  {
    _id: 11,
    name: 'Aaron Chatukuta',
    isCorporate: false,
    notes: '',
    vatOrBpNo: '',
    email: '',
    phone: '077 346 2562',
    address: '',
    balanceDue: 270,
    totalReceipts: 3000,
    isActive: false,
  },
  {
    _id: 12,
    name: 'Aaron Chatukuta',
    isCorporate: false,
    notes: '',
    vatOrBpNo: '',
    email: '',
    phone: '077 346 2562',
    address: '',
    balanceDue: 270,
    totalReceipts: 3000,
    isActive: false,
  },
  {
    _id: 13,
    name: 'Aaron Chatukuta',
    isCorporate: false,
    notes: '',
    vatOrBpNo: '',
    email: '',
    phone: '077 346 2562',
    address: '',
    balanceDue: 270,
    totalReceipts: 3000,
    isActive: false,
  },
]

export const contactsList = writable(contacts)
